# 异常定义

- 一旦程序出现异常，未处理时，就终止执行。
- 系统的运行过程中，很多问题不是靠代码就能避免的，比如：
  - 客户输入数据的格式
  - 读取文件是否存在
  - 网络是否始终保持通畅
- 异常的分类（java.lang.Throwable）
  - Error（java.lang.Error）
    - Java虚拟机无法解决的严重问题
    - 一般不编写针对性的代码进行处理
    - 举例
      - JVM系统内部错误
      - 资源耗尽等严重情况
      - 栈溢出 StackOverflowError（死循环）
      - 堆溢出 OOM（OutOfMemoryError）
        Integer[] arr = new Integer[1024*1024*1024]
  - Exception（java.lang.Exception）
    - 其他因变成错误或偶然的外在因素导致的一般性问题
    - 可以使用针对性的代码进行处理
    - 举例
      - 空指针访问
      - 试图读取不存在的文件
      - 网络连接中断
      - 数组角标越界

# 常见异常

- 常见异常

| x                              | x                                |
| ------------------------------ | -------------------------------- |
| InputMisMatchException         | 输入的数据类型与要求的类型不匹配 |
| ArrayIndexOutOfBoundsException | 数组的索引越界异常               |
| NullPointerException           | 空指针异常                       |
| StackOverflowError             | 栈溢出（一直调用方法却不返回）   |
| ClassCastException             | 类型转换异常                     |
| NumberFormatException          | 数字格式异常                     |
| IllegalThreadStateException    | 非法的线程状态                   |
| ArithmeticException            | 1/0，分母是0报错                 |

# 处理异常

## 思路

- 过多的if-else分支会导致程序的代码过长、臃肿、可读性差。因此需要采用异常处理机制。
- Java采用的异常处理机制，是将异常处理的程序代码集中在一起，与正常的程序代码分开，使得程序简洁、优雅，并易于维护。

## 抓抛模型

- 抛

  - 程序在正常执行的过程中，一旦出现异常，就会在异常代码出生成一个对应异常类的对象，并将此对象抛出

  - 一旦抛出，其后的代码就不再执行

- 抓 —— 可以理解为异常的处理方式
  - try-catch-finally
    - 自己有能力处理
    - 真正地将异常处理掉了
  - throws+异常类型
    - 喊人一起来处理，相当于一直向上反映，知道main，main再给JVM，要是一直没处理，还是会崩掉
    - 只是讲异常抛给了方法的调用者，并没有真正地讲异常处理掉。

## try-catch-finally

- 基本语法

  ```java
  try{
    //可能出现异常的代码
  }catch(异常类型1 变量名1){
    //处理异常的方式1
  }catch(异常类型2 变量名2){
    //处理异常的方式2
  }
  ....
  finally{
    //一定会执行的代码
  }
  ```

- finally是可选项

  - finally中声明的是“一定会被执行的代码”，即使catch中又出现异常了，try中有return语句等情况
  - 像数据库连接、输入输出流、网络编程Socket等资源，JVM是不能自动回收的，要求我们手动进行资源释放，资源的释放操作，就声明在finally（不管有没有异常这个操作一定要做）

- 不使用finally时候的注意点

  - 出现异常，和catch中的进行匹配，匹配到一个就处理，只处理一个就结束
  - 在try结构中声明的变量，在出了try结构以后，就不能再被调用了

- throw

  - 可抛出
    - java.lang.Exception
    - java.lang.RuntimeException //运行时异常
  - 只有异常类体系的对象才可以被throw
  - 表示抛出一个异常类的对象
  - 是生成异常对象的过程
  - 声明在*方法体内*
  - 手动抛出异常

## throws

- “throws + 异常类型”写在方法的声明处，指明此方法执行时，可能会抛出的异常类型。
- 异常一旦抛出，后面的代码就不会被执行了。
- 属于异常处理的一种方式
- 声明在方法的*声明处*

## 开发中如何选择try-catch/throws

- 如果父类中被重写的方法没有throws方式处理异常，子类重写的方法也不能使用throws，意味着如果子类重写的方法中有异常，必须使用try-catch-finally
- 执行的方法a中，先后有调用了另外的几个方法，这几个方法是递进关系进行执行的，我们建议这几个方法使用throws的方式进行处理，而执行的方法a可以考虑try-catch-finally进行处理

## 查看错误信息

```java
Exception e = new Exception();
e.getMessage();//获取异常信息
e.printStackTrace();//打印堆栈的错误信息
```

# 自定义异常类

## 定义

- 继承自现有异常结构

  - Exception
  - RuntimeException

- 仿照已有异常结构的几个固定内容

  - serialVersionUID

    ```java
    static final long serialVersionUID = xxxxxxxxx;
    ```

    

  - 提供全局常量 serialVersionUID 对类的一个标识，唯一标识Exception的类

  - 序列化机制：网络传输的时候传输的就是对象，用序列号表示是同一个类

  - 不是名字一样就可以，所以用序列号标识是不是一个类【IO流的对象流中会涉及到】
